### ISSUE TITLE
display in unit-scaling-notebook.ipynb

### ISSUE THREAD

**Issue by zhenpn** [graphcore-research/unit-scaling-demo#2]
Hi, I was wondering what is the display function in the unit-scaling-notebook.ipynb file since there is no reference.

**Comment by thecharlieblake** [comment]
This is a function that I think `IPython` automatically imports into your jupyter sessions: https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html#IPython.display.display

When you end a jupyter cell with a statement returning a value, this is the function that's implicitly called on that value to create the output you see in the notebook.

I can imagine some notebook software doesn't import this by default, but (assuming you have IPython installed and it works with your notebook) you should be able to do:
```
from IPython.display import display
```
